const posts=[
{title:'Sample Government Job Notification 2026',category:'সরকারি চাকরি',description:'এটি একটি নমুনা পোস্ট। বাস্তব নিয়োগ বিজ্ঞপ্তির তথ্য প্রকাশের আগে অফিসিয়াল বিজ্ঞপ্তি যাচাই করুন।',date:'16 September 2026',url:'posts/sample-job.html'},
{title:'Sample Admit Card Update 2026',category:'Admit Card',description:'এটি একটি নমুনা Admit Card পোস্ট। অফিসিয়াল লিঙ্ক পরে যোগ করুন।',date:'16 September 2026',url:'posts/sample-admit-card.html'},
{title:'Sample Result Update 2026',category:'Result',description:'এটি একটি নমুনা Result পোস্ট। অফিসিয়াল ফলাফল প্রকাশিত হলে তথ্য আপডেট করুন।',date:'16 September 2026',url:'posts/sample-result.html'}
];
function $(s,r=document){return r.querySelector(s)}
function $$(s,r=document){return [...r.querySelectorAll(s)]}
function initTheme(){const saved=localStorage.getItem('wbhelp-theme');if(saved==='dark')document.body.classList.add('dark');const b=$('#themeToggle');if(b)b.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('wbhelp-theme',document.body.classList.contains('dark')?'dark':'light')})}
function initMenu(){const b=$('#menuToggle'),n=$('#siteNav');if(b&&n)b.addEventListener('click',()=>n.classList.toggle('open'));$$('#siteNav a').forEach(a=>a.addEventListener('click',()=>n?.classList.remove('open')))}
function renderSearchResults(q,container){const term=q.trim().toLowerCase();if(!term){container.innerHTML='';return}const found=posts.filter(p=>`${p.title} ${p.category} ${p.description}`.toLowerCase().includes(term));if(!found.length){container.innerHTML='<div class="empty">কোনও ফলাফল পাওয়া যায়নি।</div>';return}container.innerHTML=found.map(p=>`<article class="post-card card"><div class="thumb">WB</div><div><div class="tags"><span class="tag">${p.category}</span></div><h3>${p.title}</h3><p>${p.description}</p><div class="meta">প্রকাশিত: ${p.date}</div></div><div class="post-actions"><a class="btn btn-primary" href="${p.url}">Read More</a></div></article>`).join('')}
function initSearch(){const input=$('#siteSearch'),btn=$('#searchBtn'),box=$('#searchResults');if(!input||!btn||!box)return;const run=()=>renderSearchResults(input.value,box);btn.addEventListener('click',run);input.addEventListener('keydown',e=>{if(e.key==='Enter')run()})}
function initCopyLinks(){const buttons=$$('[data-share]');buttons.forEach(b=>b.addEventListener('click',async()=>{const kind=b.dataset.share,url=location.href;try{if(kind==='copy'){await navigator.clipboard.writeText(url);b.textContent='Copied';setTimeout(()=>b.textContent='Copy Link',1200)}else if(navigator.share){await navigator.share({title:document.title,url})}}catch(e){}}))}
document.addEventListener('DOMContentLoaded',()=>{initTheme();initMenu();initSearch();initCopyLinks()});
